version: '3.8'

services:
  hiveclient_admin_client:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hiveclient_admin_client
    networks:
      - hiveclient_admin_client_network
    ports:
      - "5035:3000"
    restart: always

networks:
    hiveclient_admin_client_network:
      driver: bridge